[general]
name = "Haze Bot"

[flags]
deadlock_queue_start = true

[voice_expander.1278093581671727216]
channel_names = [
  "Bodega",
  "Garage",
  "Jazz Records",
  "Teleport Station",
  "Armory",
  "Boutique",
  "Nursery",
  "Imports",
  "Exchange",
  "Chapel",
  "Firehouse",
  "New York Oracle",
  "General Spiritism",
  "Law Firm",
  "Hotel"
]
max_channels = 5

[[game_queue]]
game_name = "Deadlock"
roles_message_id = 1282213950523572287
exclude = []

[[reaction_roles]]
message_id = 1282213950523572287
channel_id = 1282212842094854238

[reaction_roles.roles.casual_candle_trooper]
emoji_char = "ğŸ•¯ï¸"
role_id = 1282459247400976474
title = "Casual Candle Trooper"

[reaction_roles.roles.focused_lane_guardian]
emoji_char = "ğŸ”¥"
role_id = 1282459425377878037
title = "Focused Lane Guardian"

[reaction_roles.roles.experimenting_walker]
emoji_char = "âš™ï¸"
role_id = 1282466141205303340
title = "Experimenting Walker"

[[reaction_roles]]
message_id = 1282472946010558518
channel_id = 1282212842094854238

[reaction_roles.roles.stream_student]
emoji_char = "ğŸ”´"
role_id = 1282475940944809994
title = "Stream Students"

[reaction_roles.roles.theory_majors]
emoji_char = "ğŸ§ "
role_id = 1282476065268432956
title = "Theory Majors"

[reaction_roles.roles.mechanics_majors]
emoji_char = "ğŸ“ˆ"
role_id = 1282476415249416214
title = "Mechanics Major"

[reaction_roles.roles.strategy_majors]
emoji_char = "ğŸ›¤ï¸"
role_id = 1282476935724793876
title = "Strategy Majors"
