[general]
name = "Haze Bot"

[flags]
deadlock_queue_start = true

[[game_queue]]
game_name = "Deadlock"
roles_message_id = 1282242118945083413
exclude = []

[[reaction_roles]]
message_id = 1282242118945083413
create_message_if_not_exists = true

[reaction_roles.roles.casual_candle_trooper]
emoji_char = "ğŸ•¯ï¸"
role_id = 1282242176201527331 
title = "Casual Candle Trooper"

[reaction_roles.roles.try-hard_lane_guardian]
emoji_char = "ğŸ”¥"
role_id = 1282242281247871069
title = "Try-Hard Lane Guardian"
